/**
 * Writes a SYNTHETIC sample dataset for developing and testing the parcel map:
 *   data/land-map/synthetic/manifest.json + parcels.geojson
 *
 *   pnpm tsx scripts/land-map/make-synthetic.ts
 *   pnpm land-map:import data/land-map/synthetic/manifest.json --allow-synthetic
 *
 * These polygons are generated, not surveyed: an irregular grid of made-up
 * plots with made-up numbers ("SYN-…") in a made-up village. They are marked
 * synthetic in the database, drawn with a "sample" style and banner, and are
 * never served unless LAND_PARCEL_MAP_SYNTHETIC=true outside Vercel production.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const OUT = join(process.cwd(), "data/land-map/synthetic");

// Deterministic pseudo-random numbers so the file is identical on every run.
let seed = 42;
const rand = () => ((seed = (seed * 1103515245 + 12345) % 2 ** 31) / 2 ** 31);

const origin = { lng: 77.5205, lat: 28.4605 }; // an open area; the village name below is fictitious
const cols = 12;
const rows = 8;
const dLng = 0.00042; // ≈ 41 m
const dLat = 0.00036; // ≈ 40 m

const corner = (c: number, r: number): [number, number] => {
  // Jitter interior corners so plots look irregular; the outer edge stays straight.
  const jx = c > 0 && c < cols ? (rand() - 0.5) * dLng * 0.35 : 0;
  const jy = r > 0 && r < rows ? (rand() - 0.5) * dLat * 0.35 : 0;
  return [+(origin.lng + c * dLng + jx).toFixed(7), +(origin.lat + r * dLat + jy).toFixed(7)];
};
const grid: [number, number][][] = [];
for (let c = 0; c <= cols; c++) {
  grid[c] = [];
  for (let r = 0; r <= rows; r++) grid[c][r] = corner(c, r);
}

const features = [];
let n = 0;
for (let r = 0; r < rows; r++) {
  for (let c = 0; c < cols; c++) {
    n++;
    const ring = [grid[c][r], grid[c + 1][r], grid[c + 1][r + 1], grid[c][r + 1], grid[c][r]];
    features.push({
      type: "Feature",
      properties: {
        SYN_ID: `SYN-${String(n).padStart(4, "0")}`,
        PLOT_NO: `${n}${n % 7 === 0 ? "/1" : ""}`,
        VILLAGE: "Synthetic Test Village (sample)",
        VILL_CODE: "SYN000",
        TEHSIL: "Dadri",
        AREA_HA: +(0.12 + rand() * 0.1).toFixed(4),
        CLASS: ["Agricultural (sample)", "Abadi (sample)", "Banjar (sample)"][n % 3],
        UPDATED: "2026-10-01",
      },
      geometry: { type: "Polygon", coordinates: [ring] },
    });
  }
}

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, "parcels.geojson"), `${JSON.stringify({ type: "FeatureCollection", features })}\n`);
writeFileSync(
  join(OUT, "manifest.json"),
  `${JSON.stringify(
    {
      dataset: {
        key: "synthetic-gbn-sample",
        name: "SYNTHETIC sample parcels (not real data)",
        sourceName: "Generated by scripts/land-map/make-synthetic.ts",
        license: "Synthetic test data — no real-world meaning",
        attribution: "Synthetic sample — not government data",
        isSynthetic: true,
        stateName: "Uttar Pradesh",
        districtName: "Gautam Buddha Nagar",
        acquiredAt: "2026-10-11",
        sourceUpdatedAt: "2026-10-01",
        notes: "Made-up plots for testing rendering, selection and search. Do not use for any decision.",
      },
      file: "parcels.geojson",
      crs: "EPSG:4326",
      fields: {
        recordId: "SYN_ID",
        parcelNumber: "PLOT_NO",
        villageName: "VILLAGE",
        villageCode: "VILL_CODE",
        tehsilName: "TEHSIL",
        recordedArea: "AREA_HA",
        landClass: "CLASS",
        sourceUpdatedAt: "UPDATED",
      },
      defaults: { recordedAreaUnit: "hectare" },
    },
    null,
    2,
  )}\n`,
);
console.log(`Wrote ${features.length} synthetic parcels to ${OUT}`);
